name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json

      - name: Install UI dependencies
        working-directory: ./ui
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./ui
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./ui
        run: npm run test:e2e

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ui/playwright-report/
          retention-days: 30

  test-api-integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: testuser
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install API dependencies
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup test environment
        working-directory: ./api
        env:
          DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb
          APP_USER_HASH_BCRYPT: $2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj6o6a7c0pF.
          SESSION_SECRET: test-secret-key-for-ci
          UI_ORIGIN: http://localhost:4321
        run: |
          python -m app.migrate
          python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5

      - name: Install UI dependencies
        working-directory: ./ui
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./ui
        run: npx playwright install --with-deps

      - name: Run E2E tests with real API
        working-directory: ./ui
        env:
          API_URL: http://localhost:8000
        run: |
          # Create a special config for API integration tests
          cat > playwright-api.config.ts << 'EOF'
          import { defineConfig } from '@playwright/test';
          import config from './playwright.config';

          export default defineConfig({
            ...config,
            testDir: './tests/api-integration',
            use: {
              ...config.use,
              baseURL: 'http://localhost:4321',
            },
            webServer: {
              command: 'npm run dev',
              url: 'http://localhost:4321',
              reuseExistingServer: false,
              timeout: 120 * 1000,
            },
          });
          EOF

          # Run tests with real API
          npm run test:e2e -- --config=playwright-api.config.ts || true

      - name: Upload API Integration Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-api-report
          path: ui/playwright-report/
          retention-days: 30
